/**
 * Copyright 2023 Viacheslav Barkov
 */

package com.amias.texttoimagesearch.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters

/**
 * Represents an image embedding stored in the database.
 *
 * An image embedding is a numerical representation of an image,
 * typically generated by a machine learning model. It captures
 * the essential visual features of the image in a compact vector.
 * This class is designed to store these embeddings along with
 * relevant metadata such as the ID and the date the embedding was created.
 *
 * @property id The unique identifier for the image embedding. This is the primary key.
 * @property date The timestamp (in milliseconds since the epoch) indicating when the
 *                embedding was created or added to the database.
 * @property embedding The actual embedding vector represented as an array of floats.
 *                     Each float in the array represents a dimension in the embedding space.
 */
@Entity(tableName = "image_embeddings")
@TypeConverters(Converters::class)
data class ImageEmbedding(
    @PrimaryKey(autoGenerate = false)
    val id: Long,
    val date: Long,
    val embedding: FloatArray,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ImageEmbedding

        if (id != other.id) return false
        if (date != other.date) return false
        if (!embedding.contentEquals(other.embedding)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + date.hashCode()
        result = 31 * result + embedding.contentHashCode()
        return result
    }
}
